In [1]:
import pandas as pd
import numpy as np

In [29]:
from catboost import CatBoostClassifier

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

In [2]:
df=pd.read_csv("D:/Downloads/Final_Attrition_Dataset_200_Employees.csv")

In [3]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Job_Level', 'Work_Mode',
       'Shift_Type', 'Tenure_Months', 'Monthly_Salary_PKR',
       'Salary_vs_Market_pct', 'Last_Increment_pct',
       'Months_Since_Last_Promotion', 'KPI_Achievement_pct',
       'Performance_Trend_6M', 'Overtime_Hours_Last_30D',
       'Absence_Days_Last_90D', 'Engagement_Score', 'Job_Satisfaction_Score',
       'Work_Life_Balance_Score', 'Manager_Relationship_Score',
       'Career_Growth_Score', 'Commute_Minutes_One_Way',
       'Manager_Changed_Last_6M', 'Pay_Concern_Raised_Last_6M',
       'Will_Resign_in_Next_6_Months'],
      dtype='str')

In [4]:
df.head()

,Employee_ID,Employee_Name,Department,Job_Level,Work_Mode,Shift_Type,Tenure_Months,Monthly_Salary_PKR,Salary_vs_Market_pct,Last_Increment_pct,...,Absence_Days_Last_90D,Engagement_Score,Job_Satisfaction_Score,Work_Life_Balance_Score,Manager_Relationship_Score,Career_Growth_Score,Commute_Minutes_One_Way,Manager_Changed_Last_6M,Pay_Concern_Raised_Last_6M,Will_Resign_in_Next_6_Months
0,EMP001,Sonia Hassan,HR,Lead/Manager,Hybrid,Day,140,233000,5.3,5.7,...,0,3.7,4.5,4.4,3.9,2.1,33,No,No,Yes
1,EMP002,Bilal Aziz,Sales,Mid,Onsite,Rotational,37,132000,19.5,8.8,...,0,5.0,5.0,4.1,4.9,3.5,53,No,No,No
2,EMP003,Kamran Ali,Finance,Mid,Remote,Day,14,100000,-8.9,5.5,...,2,3.8,4.3,4.7,4.2,4.4,5,No,No,No
3,EMP004,Ali Masood,Finance,Mid,Onsite,Day,39,96000,-13.0,2.8,...,2,3.3,2.8,2.9,3.7,3.3,35,No,Yes,Yes
4,EMP005,Farhan Shah,Engineering,Junior,Remote,Day,16,72000,4.8,6.9,...,1,3.0,3.9,4.1,1.8,4.8,1,No,No,Yes

In [ ]:
df.drop(columns= ['Employee_ID','Employee_Name','Work_Mode','Manager_Changed_Last_6M','Job_Level','Shift_Type','Commute_Minutes_One_Way','Absence_Days_Last_90D','Department'], inplace=True)

In [16]:
df.head()

,Tenure_Months,Monthly_Salary_PKR,Salary_vs_Market_pct,Last_Increment_pct,Months_Since_Last_Promotion,KPI_Achievement_pct,Performance_Trend_6M,Overtime_Hours_Last_30D,Engagement_Score,Job_Satisfaction_Score,Work_Life_Balance_Score,Manager_Relationship_Score,Career_Growth_Score,Pay_Concern_Raised_Last_6M,Will_Resign_in_Next_6_Months
0,140,233000,5.3,5.7,71,100.1,0.5,4,3.7,4.5,4.4,3.9,2.1,No,Yes
1,37,132000,19.5,8.8,23,99.2,0.5,8,5.0,5.0,4.1,4.9,3.5,No,No
2,14,100000,-8.9,5.5,12,104.9,0.2,0,3.8,4.3,4.7,4.2,4.4,No,No
3,39,96000,-13.0,2.8,25,107.0,-0.1,32,3.3,2.8,2.9,3.7,3.3,Yes,Yes
4,16,72000,4.8,6.9,13,73.1,-0.0,14,3.0,3.9,4.1,1.8,4.8,No,Yes

In [17]:
target = "Will_Resign_in_Next_6_Months"

In [21]:
x = df.drop(
    columns=[
        target
    ]
)

In [22]:
x.head()

,Tenure_Months,Monthly_Salary_PKR,Salary_vs_Market_pct,Last_Increment_pct,Months_Since_Last_Promotion,KPI_Achievement_pct,Performance_Trend_6M,Overtime_Hours_Last_30D,Engagement_Score,Job_Satisfaction_Score,Work_Life_Balance_Score,Manager_Relationship_Score,Career_Growth_Score,Pay_Concern_Raised_Last_6M
0,140,233000,5.3,5.7,71,100.1,0.5,4,3.7,4.5,4.4,3.9,2.1,No
1,37,132000,19.5,8.8,23,99.2,0.5,8,5.0,5.0,4.1,4.9,3.5,No
2,14,100000,-8.9,5.5,12,104.9,0.2,0,3.8,4.3,4.7,4.2,4.4,No
3,39,96000,-13.0,2.8,25,107.0,-0.1,32,3.3,2.8,2.9,3.7,3.3,Yes
4,16,72000,4.8,6.9,13,73.1,-0.0,14,3.0,3.9,4.1,1.8,4.8,No

In [23]:
y=y = df[target].map({
    "No": 0,
    "Yes": 1
})

In [26]:
from sklearn.model_selection import train_test_split

# Split data: 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y)

In [28]:
X_test.shape

(40, 14)

In [30]:
X_train_final, X_val, y_train_final, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

print("Final training shape:", X_train_final.shape)
print("Validation shape:", X_val.shape)
print("Testing shape:", X_test.shape)

print("\nTraining target:")
print(y_train_final.value_counts())

print("\nValidation target:")
print(y_val.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

Final training shape: (128, 14)
Validation shape: (32, 14)
Testing shape: (40, 14)

Training target:
Will_Resign_in_Next_6_Months
0    64
1    64
Name: count, dtype: int64

Validation target:
Will_Resign_in_Next_6_Months
1    16
0    16
Name: count, dtype: int64

Testing target:
Will_Resign_in_Next_6_Months
0    20
1    20
Name: count, dtype: int64

In [31]:
#diffrentiating numerical and categorical columns
categorical_features = X_train_final.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

numerical_features = X_train_final.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
['Pay_Concern_Raised_Last_6M']

Numerical features:
['Tenure_Months', 'Monthly_Salary_PKR', 'Salary_vs_Market_pct', 'Last_Increment_pct', 'Months_Since_Last_Promotion', 'KPI_Achievement_pct', 'Performance_Trend_6M', 'Overtime_Hours_Last_30D', 'Engagement_Score', 'Job_Satisfaction_Score', 'Work_Life_Balance_Score', 'Manager_Relationship_Score', 'Career_Growth_Score']

C:\Users\ALLAH\AppData\Local\Temp\ipykernel_13208\2900152650.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X_train_final.select_dtypes(

In [36]:
#importing catboost modeel
catboost_model = CatBoostClassifier(

    # Maximum number of boosting iterations
    iterations=500,

    # Small learning rate for controlled learning
    learning_rate=0.03,

    # Tree depth kept moderate because dataset is small
    depth=4,

    # Binary classification loss
    loss_function="Logloss",

    # Validation metric
    eval_metric="Logloss",

    # Regularization
    l2_leaf_reg=10,

    # Adds controlled randomness
    random_strength=2,

    # Reproducibility
    random_seed=42,
    bagging_temperature=1,
    # Display result after every 50 iterations
    verbose=25,

    # Avoid creating unnecessary CatBoost folders
    allow_writing_files=False
)

In [44]:
catboost_model.fit(

    X_train_final,
    y_train_final,

    # Names of categorical columns
    cat_features=categorical_features,

    # Validation data
    eval_set=(X_val, y_val),

    # Stop when validation performance does not improve
    early_stopping_rounds=40,

    # Keep best-performing iteration
    use_best_model=True
)

0:	learn: 0.6772110	test: 0.6754174	best: 0.6754174 (0)	total: 5.48ms	remaining: 2.73s
25:	learn: 0.4511645	test: 0.4599344	best: 0.4599344 (25)	total: 122ms	remaining: 2.23s
50:	learn: 0.3609960	test: 0.3826059	best: 0.3826059 (50)	total: 207ms	remaining: 1.82s
75:	learn: 0.3105006	test: 0.3559593	best: 0.3559593 (75)	total: 274ms	remaining: 1.53s
100:	learn: 0.2769983	test: 0.3397311	best: 0.3397311 (100)	total: 317ms	remaining: 1.25s
125:	learn: 0.2477154	test: 0.3281632	best: 0.3258436 (121)	total: 362ms	remaining: 1.07s
150:	learn: 0.2231315	test: 0.3254282	best: 0.3241731 (137)	total: 407ms	remaining: 942ms
175:	learn: 0.2003953	test: 0.3278051	best: 0.3241731 (137)	total: 462ms	remaining: 850ms
Stopped by overfitting detector  (40 iterations wait)

bestTest = 0.3241731357
bestIteration = 137

Shrink model to first 138 iterations.

CatBoostClassifier(allow_writing_files=False, bagging_temperature=1, depth=4, eval_metric='Logloss', iterations=500, l2_leaf_reg=10, learning_rate=0.03, loss_function='Logloss', random_seed=42, random_strength=2, verbose=25)

In [45]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

# Predictions
y_probability = catboost_model.predict_proba(
    X_test
)[:, 1]

y_pred = (
    y_probability >= best_threshold
).astype(int)
y_pred = y_pred.astype(int).ravel()

# Resignation probabilities
y_prob = catboost_model.predict_proba(X_test)[:, 1]

print("Accuracy :", round(accuracy_score(y_test, y_pred), 4))
print("Precision:", round(precision_score(y_test, y_pred), 4))
print("Recall   :", round(recall_score(y_test, y_pred), 4))
print("F1 Score :", round(f1_score(y_test, y_pred), 4))
print("ROC-AUC  :", round(roc_auc_score(y_test, y_prob), 4))

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Will Not Resign", "Will Resign"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.75
Precision: 0.7273
Recall   : 0.8
F1 Score : 0.7619
ROC-AUC  : 0.8975

Classification Report:
                 precision    recall  f1-score   support

Will Not Resign       0.78      0.70      0.74        20
    Will Resign       0.73      0.80      0.76        20

       accuracy                           0.75        40
      macro avg       0.75      0.75      0.75        40
   weighted avg       0.75      0.75      0.75        40


Confusion Matrix:
[[14  6]
 [ 4 16]]

In [46]:
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


def evaluate_catboost(model, X_data, y_data, dataset_name):

    predictions = model.predict(
        X_data
    ).astype(int).ravel()

    probabilities = model.predict_proba(
        X_data
    )[:, 1]

    return {
        "Dataset": dataset_name,
        "Accuracy": accuracy_score(
            y_data,
            predictions
        ),
        "Precision": precision_score(
            y_data,
            predictions,
            zero_division=0
        ),
        "Recall": recall_score(
            y_data,
            predictions,
            zero_division=0
        ),
        "F1": f1_score(
            y_data,
            predictions,
            zero_division=0
        ),
        "ROC_AUC": roc_auc_score(
            y_data,
            probabilities
        )
    }


results = pd.DataFrame([
    evaluate_catboost(
        catboost_model,
        X_train_final,
        y_train_final,
        "Training"
    ),

    evaluate_catboost(
        catboost_model,
        X_val,
        y_val,
        "Validation"
    ),

    evaluate_catboost(
        catboost_model,
        X_test,
        y_test,
        "Testing"
    )
])

print(results.round(4))

      Dataset  Accuracy  Precision  Recall      F1  ROC_AUC
0    Training    0.9297     0.8986  0.9688  0.9323   0.9846
1  Validation    0.9062     0.8824  0.9375  0.9091   0.9297
2     Testing    0.7750     0.7619  0.8000  0.7805   0.8975

In [47]:
# Save trained CatBoost model
catboost_model.save_model(
    "CatBoost_Attrition_Model.cbm"
)

print("Model saved successfully.")

Model saved successfully.

In [48]:
from pathlib import Path

# Folder jahan model save karna hai
model_folder = Path(r"D:\Attrition_Project\models")

# Folder na ho to automatically create ho jayega
model_folder.mkdir(parents=True, exist_ok=True)

# Complete model path
model_path = model_folder / "catboost_attrition_model.cbm"

# Save trained model
catboost_model.save_model(
    str(model_path),
    format="cbm"
)

print("Model saved successfully at:")
print(model_path)

Model saved successfully at:
D:\Attrition_Project\models\catboost_attrition_model.cbm

In [59]:
#now training the random forest
# 1. Libraries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)


# 2. Categorical aur numerical columns
categorical_columns = X_train.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

numerical_columns = X_train.select_dtypes(
    exclude=["object", "category", "bool"]
).columns.tolist()


# 3. Data preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            Pipeline([
                ("missing", SimpleImputer(strategy="most_frequent")),
                ("encoding", OneHotEncoder(handle_unknown="ignore"))
            ]),
            categorical_columns
        ),
        (
            "numerical",
            SimpleImputer(strategy="median"),
            numerical_columns
        )
    ]
)


# 4. Random Forest model
random_forest_model = Pipeline([
    ("preprocessing", preprocessor),

    ("model", RandomForestClassifier(
        n_estimators=500,
        max_depth=5,
        min_samples_leaf=3,
        random_state=42,
        n_jobs=-1
    ))
])


# 5. Train model
random_forest_model.fit(X_train, y_train)

print("Random Forest training complete.")

C:\Users\ALLAH\AppData\Local\Temp\ipykernel_13208\643072272.py:21: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X_train.select_dtypes(

Random Forest training complete.

In [60]:
# Predictions
y_pred_rf = random_forest_model.predict(X_test)

# Probabilities
y_prob_rf = random_forest_model.predict_proba(X_test)[:, 1]


print("Accuracy :", round(accuracy_score(y_test, y_pred_rf), 4))
print("Precision:", round(precision_score(y_test, y_pred_rf), 4))
print("Recall   :", round(recall_score(y_test, y_pred_rf), 4))
print("F1 Score :", round(f1_score(y_test, y_pred_rf), 4))
print("ROC-AUC  :", round(roc_auc_score(y_test, y_prob_rf), 4))

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_rf,
    target_names=["Will Not Resign", "Will Resign"]
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Accuracy : 0.775
Precision: 0.7391
Recall   : 0.85
F1 Score : 0.7907
ROC-AUC  : 0.895

Classification Report:
                 precision    recall  f1-score   support

Will Not Resign       0.82      0.70      0.76        20
    Will Resign       0.74      0.85      0.79        20

       accuracy                           0.78        40
      macro avg       0.78      0.77      0.77        40
   weighted avg       0.78      0.78      0.77        40

Confusion Matrix:
[[14  6]
 [ 3 17]]

In [61]:
#checking overfitting 
train_pred_rf = random_forest_model.predict(X_train)

train_accuracy = accuracy_score(y_train, train_pred_rf)
test_accuracy = accuracy_score(y_test, y_pred_rf)

print("Training Accuracy:", round(train_accuracy, 4))
print("Testing Accuracy :", round(test_accuracy, 4))
print("Accuracy Gap     :", round(train_accuracy - test_accuracy, 4))

Training Accuracy: 0.9187
Testing Accuracy : 0.775
Accuracy Gap     : 0.1437